// This file is automatically generated by qtc from "base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// Base template interface
//

//line templates/base.qtpl:3
package templates

//line templates/base.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/base.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:4
type Page interface {
	//line templates/base.qtpl:4
	Title() string
	//line templates/base.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
	//line templates/base.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
	//line templates/base.qtpl:4
	Body() string
	//line templates/base.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
	//line templates/base.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line templates/base.qtpl:4
}

//line templates/base.qtpl:10
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line templates/base.qtpl:10
	qw422016.N().S(`
<html>
	<head>
		<title>`)
	//line templates/base.qtpl:13
	p.StreamTitle(qw422016)
	//line templates/base.qtpl:13
	qw422016.N().S(`</title>
	</head>
	<body>
		<div>
			<a href="/">List Of Users</a>
		</div>
		<div>
			<a href="/get">Add New User</a>
		</div>
		`)
	//line templates/base.qtpl:22
	p.StreamBody(qw422016)
	//line templates/base.qtpl:22
	qw422016.N().S(`
	</body>
</html>
`)
//line templates/base.qtpl:25
}

//line templates/base.qtpl:25
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line templates/base.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/base.qtpl:25
	StreamPageTemplate(qw422016, p)
	//line templates/base.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:25
}

//line templates/base.qtpl:25
func PageTemplate(p Page) string {
	//line templates/base.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/base.qtpl:25
	WritePageTemplate(qb422016, p)
	//line templates/base.qtpl:25
	qs422016 := string(qb422016.B)
	//line templates/base.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/base.qtpl:25
	return qs422016
//line templates/base.qtpl:25
}
