// This file is automatically generated by qtc from "main.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// The list page template
//

//line templates/main.qtpl:3
package templates

//line templates/main.qtpl:3
import "structs"

//line templates/main.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/main.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/main.qtpl:6
type MainPage struct {
	Users []*structs.User
}

//line templates/main.qtpl:12
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line templates/main.qtpl:12
	qw422016.N().S(`
	Users List
`)
//line templates/main.qtpl:14
}

//line templates/main.qtpl:14
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line templates/main.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/main.qtpl:14
	p.StreamTitle(qw422016)
	//line templates/main.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line templates/main.qtpl:14
}

//line templates/main.qtpl:14
func (p *MainPage) Title() string {
	//line templates/main.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/main.qtpl:14
	p.WriteTitle(qb422016)
	//line templates/main.qtpl:14
	qs422016 := string(qb422016.B)
	//line templates/main.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/main.qtpl:14
	return qs422016
//line templates/main.qtpl:14
}

//line templates/main.qtpl:17
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
	//line templates/main.qtpl:17
	qw422016.N().S(`
	<h1>List</h1>
	`)
	//line templates/main.qtpl:19
	if len(p.Users) == 0 {
		//line templates/main.qtpl:19
		qw422016.N().S(`
		No users yet..
	`)
		//line templates/main.qtpl:21
	} else {
		//line templates/main.qtpl:21
		qw422016.N().S(`
		<div>
			<table border="1">
				<tr>
					<td>
						<b>ID</b>
					</td>
					<td>
						<b>Fisrt Name</b>
					</td>
					<td>
						<b>Last Name</b>
					</td>
					<td>
						<b>Created Date</b>
					</td>
					<td>
						<b>Edit</b>
					</td>
				</tr>
				`)
		//line templates/main.qtpl:41
		for _, val := range p.Users {
			//line templates/main.qtpl:41
			qw422016.N().S(`
				<tr>
					<td>
						`)
			//line templates/main.qtpl:44
			qw422016.N().D(val.Id)
			//line templates/main.qtpl:44
			qw422016.N().S(`
					</td>
					<td>
						`)
			//line templates/main.qtpl:47
			qw422016.E().S(val.FirstName)
			//line templates/main.qtpl:47
			qw422016.N().S(`
					</td>
					<td>
						`)
			//line templates/main.qtpl:50
			qw422016.E().S(val.LastName)
			//line templates/main.qtpl:50
			qw422016.N().S(`
					</td>
					<td>
						`)
			//line templates/main.qtpl:53
			qw422016.E().S(val.CreatedDate.Format("2006-01-02 15:04:05"))
			//line templates/main.qtpl:53
			qw422016.N().S(`
					</td>
					<td>
						<a href="/get/`)
			//line templates/main.qtpl:56
			qw422016.N().D(val.Id)
			//line templates/main.qtpl:56
			qw422016.N().S(`">Edit</a>
					</td>
				</tr>
				`)
			//line templates/main.qtpl:59
		}
		//line templates/main.qtpl:59
		qw422016.N().S(`
			</table>
		</div>
	`)
		//line templates/main.qtpl:62
	}
	//line templates/main.qtpl:62
	qw422016.N().S(`
`)
//line templates/main.qtpl:63
}

//line templates/main.qtpl:63
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
	//line templates/main.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/main.qtpl:63
	p.StreamBody(qw422016)
	//line templates/main.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line templates/main.qtpl:63
}

//line templates/main.qtpl:63
func (p *MainPage) Body() string {
	//line templates/main.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/main.qtpl:63
	p.WriteBody(qb422016)
	//line templates/main.qtpl:63
	qs422016 := string(qb422016.B)
	//line templates/main.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/main.qtpl:63
	return qs422016
//line templates/main.qtpl:63
}
