// This file is automatically generated by qtc from "user.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/user.qtpl:1
package templates

//line templates/user.qtpl:1
import "structs"

//line templates/user.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/user.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/user.qtpl:4
type UserPage struct {
	User *structs.User
}

//line templates/user.qtpl:10
func (u *UserPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line templates/user.qtpl:10
	qw422016.N().S(`
	`)
	//line templates/user.qtpl:11
	if u.User == nil {
		//line templates/user.qtpl:11
		qw422016.N().S(`
		Add New User
	`)
		//line templates/user.qtpl:13
	} else {
		//line templates/user.qtpl:13
		qw422016.N().S(`
		Edit User
	`)
		//line templates/user.qtpl:15
	}
	//line templates/user.qtpl:15
	qw422016.N().S(`
`)
//line templates/user.qtpl:16
}

//line templates/user.qtpl:16
func (u *UserPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line templates/user.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/user.qtpl:16
	u.StreamTitle(qw422016)
	//line templates/user.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line templates/user.qtpl:16
}

//line templates/user.qtpl:16
func (u *UserPage) Title() string {
	//line templates/user.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/user.qtpl:16
	u.WriteTitle(qb422016)
	//line templates/user.qtpl:16
	qs422016 := string(qb422016.B)
	//line templates/user.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/user.qtpl:16
	return qs422016
//line templates/user.qtpl:16
}

//line templates/user.qtpl:19
func (u *UserPage) StreamBody(qw422016 *qt422016.Writer) {
	//line templates/user.qtpl:19
	qw422016.N().S(`
	<h1>
	`)
	//line templates/user.qtpl:21
	first := ""

	//line templates/user.qtpl:21
	qw422016.N().S(`
	`)
	//line templates/user.qtpl:22
	last := ""

	//line templates/user.qtpl:22
	qw422016.N().S(`
	`)
	//line templates/user.qtpl:23
	id := -1

	//line templates/user.qtpl:23
	qw422016.N().S(`
	`)
	//line templates/user.qtpl:24
	if u.User == nil {
		//line templates/user.qtpl:24
		qw422016.N().S(`
		New User
	`)
		//line templates/user.qtpl:26
	} else {
		//line templates/user.qtpl:26
		qw422016.N().S(`
		Edit User #`)
		//line templates/user.qtpl:27
		qw422016.N().D(u.User.Id)
		//line templates/user.qtpl:27
		qw422016.N().S(`
		`)
		//line templates/user.qtpl:28
		first = u.User.FirstName

		//line templates/user.qtpl:28
		qw422016.N().S(`
		`)
		//line templates/user.qtpl:29
		last = u.User.LastName

		//line templates/user.qtpl:29
		qw422016.N().S(`
		`)
		//line templates/user.qtpl:30
		id = u.User.Id

		//line templates/user.qtpl:30
		qw422016.N().S(`
	`)
		//line templates/user.qtpl:31
	}
	//line templates/user.qtpl:31
	qw422016.N().S(`
	</h1>
	<div>
		<form method="POST" action="/add">
			<table>
				<tr>
					<td>
						Fisrt Name
					</td>
					<td>
						<input type="text" name="first" value="`)
	//line templates/user.qtpl:41
	qw422016.E().S(first)
	//line templates/user.qtpl:41
	qw422016.N().S(`" />
					</td>
				</tr>
				<tr>
					<td>
						Last Name
					</td>
					<td>
						<input type="text" name="last" value="`)
	//line templates/user.qtpl:49
	qw422016.E().S(last)
	//line templates/user.qtpl:49
	qw422016.N().S(`" />
					</td>
				</tr>
				<tr>
					<td>
						<input type="hidden" name="id" value="`)
	//line templates/user.qtpl:54
	qw422016.N().D(id)
	//line templates/user.qtpl:54
	qw422016.N().S(`" />
						<input type="submit" value="Save!" />
					</td>
				</tr>
			</table>
		</form>
	</div>
`)
//line templates/user.qtpl:61
}

//line templates/user.qtpl:61
func (u *UserPage) WriteBody(qq422016 qtio422016.Writer) {
	//line templates/user.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/user.qtpl:61
	u.StreamBody(qw422016)
	//line templates/user.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line templates/user.qtpl:61
}

//line templates/user.qtpl:61
func (u *UserPage) Body() string {
	//line templates/user.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/user.qtpl:61
	u.WriteBody(qb422016)
	//line templates/user.qtpl:61
	qs422016 := string(qb422016.B)
	//line templates/user.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/user.qtpl:61
	return qs422016
//line templates/user.qtpl:61
}
